workspaces_directory: /home/seth/Software/dev/filter/workspaces
projects_directory: /home/seth/Software/dev/filter/projects
kanban_directory: ./kanban
git_author_name: Filter Bot
git_author_email: bot@filter-kanban.dev
base_branch: main